version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: print_hub
    ports:
      - "55432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: api-dev
    depends_on:
      - db
      - mailhog
    environment:
      APP_ENV: development
      PORT: 8080
      PUBLIC_URL: http://localhost:8080
      FRONTEND_URL: http://localhost:3000
      POSTGRES_DSN: postgres://postgres:postgres@db:5432/print_hub?sslmode=disable
      JWT_SECRET: super-secret-key
      MAILGUN_DOMAIN: sandbox.example.com
      MAILGUN_API_KEY: ""
      MAILGUN_FROM: "3DPrint Hub <noreply@example.com>"
      STORAGE_UPLOADS_PATH: storage/uploads
    volumes:
      - ./apps/api:/app
      - go-cache:/go/pkg/mod
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: web-dev
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1
    command: npm run dev -- --hostname 0.0.0.0
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  db-data:
  node-modules:
  go-cache:
