# Air configuration file
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  delay = 1000
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "storage/uploads"]

[log]
  time = true
